export  enum PostEnum {
  GET_REQUEST = '[GET REQUEST] Posts',
  GET_RESPONSE = '[GET RESPONSE] Posts',
  POST_REQUEST = '[POST REQUEST] Posts',
  POST_RESPONSE = '[POST RESPONSE] Posts',
  PUT_REQUEST = '[PUT REQUEST] Posts',
  PUT_RESPONSE = '[PUT RESPONSE] Posts',
  DELETE_REQUEST = '[DELETE REQUEST] Posts',
  DELETE_RESPONSE = '[DELETE RESPONSE] Posts',
}

